header_paths = [
    # Lumberingjack stuff
    '../../Pods/CocoaLumberjack/Classes/',
    '../../Pods/Headers/Public/',

    # PubNub
    './Core',
    './Data',
    './Data/Managers',
    './Data/Service Objects',
    './Misc',
    './Misc/Helpers',
    './Misc/Logger',
    './Misc/Protocols',
    './Network',
    './Network/Parsers',
    './PubNub',
    '.',
]

defines = {
    'PGDROID' : 1,
}

flags = [
    '-fobjc-arc',
    '-Wall',
    #'-Werror', ... sigh ... maybe someday
]

deps = [
]

sources = [
    # Lumberingjack stuff
    '../../Pods/CocoaLumberjack/Classes/DDASLLogCapture.m',
    '../../Pods/CocoaLumberjack/Classes/DDASLLogger.m',
    '../../Pods/CocoaLumberjack/Classes/DDAbstractDatabaseLogger.m',
    '../../Pods/CocoaLumberjack/Classes/DDFileLogger.m',
    '../../Pods/CocoaLumberjack/Classes/DDLog.m',
    '../../Pods/CocoaLumberjack/Classes/DDTTYLogger.m',

    # PubNub stuffs
    './Core/PubNub+APNS.m',
    './Core/PubNub+ChannelGroup.m',
    './Core/PubNub+Core.m',
    './Core/PubNub+History.m',
    './Core/PubNub+Presence.m',
    './Core/PubNub+Publish.m',
    './Core/PubNub+State.m',
    './Core/PubNub+Subscribe.m',
    './Core/PubNub+Time.m',
    './Data/Managers/PNClientState.m',
    './Data/Managers/PNHeartbeat.m',
    './Data/Managers/PNStateListener.m',
    './Data/Managers/PNSubscriber.m',
    './Data/PNAES.m',
    './Data/PNConfiguration.m',
    './Data/Service Objects/PNAcknowledgmentStatus.m',
    './Data/Service Objects/PNAPNSEnabledChannelsResult.m',
    './Data/Service Objects/PNChannelClientStateResult.m',
    './Data/Service Objects/PNChannelGroupChannelsResult.m',
    './Data/Service Objects/PNChannelGroupClientStateResult.m',
    './Data/Service Objects/PNChannelGroupsResult.m',
    './Data/Service Objects/PNClientStateUpdateStatus.m',
    './Data/Service Objects/PNErrorStatus.m',
    './Data/Service Objects/PNHistoryResult.m',
    './Data/Service Objects/PNPresenceChannelGroupHereNowResult.m',
    './Data/Service Objects/PNPresenceChannelHereNowResult.m',
    './Data/Service Objects/PNPresenceGlobalHereNowResult.m',
    './Data/Service Objects/PNPresenceWhereNowResult.m',
    './Data/Service Objects/PNPublishStatus.m',
    './Data/Service Objects/PNResult.m',
    './Data/Service Objects/PNServiceData.m',
    './Data/Service Objects/PNStatus.m',
    './Data/Service Objects/PNSubscriberResults.m',
    './Data/Service Objects/PNSubscribeStatus.m',
    './Data/Service Objects/PNTimeResult.m',
    './Misc/Helpers/PNArray.m',
    './Misc/Helpers/PNChannel.m',
    './Misc/Helpers/PNClass.m',
    './Misc/Helpers/PNData.m',
    './Misc/Helpers/PNDictionary.m',
    './Misc/Helpers/PNGZIP.m',
    './Misc/Helpers/PNJSON.m',
    './Misc/Helpers/PNString.m',
    './Misc/Helpers/PNURLRequest.m',
    './Misc/Logger/PNLog.m',
    './Misc/Logger/PNLogFileManager.m',
    './Misc/Logger/PNLogger.m',
    './Network/Parsers/PNChannelGroupAuditionParser.m',
    './Network/Parsers/PNChannelGroupModificationParser.m',
    './Network/Parsers/PNClientStateParser.m',
    './Network/Parsers/PNErrorParser.m',
    './Network/Parsers/PNHeartbeatParser.m',
    './Network/Parsers/PNHistoryParser.m',
    './Network/Parsers/PNLeaveParser.m',
    './Network/Parsers/PNMessagePublishParser.m',
    './Network/Parsers/PNPresenceHereNowParser.m',
    './Network/Parsers/PNPresenceWhereNowParser.m',
    './Network/Parsers/PNPushNotificationsAuditParser.m',
    './Network/Parsers/PNPushNotificationsStateModificationParser.m',
    './Network/Parsers/PNRemoveDeviceFromAPNSResponseParser.m',
    './Network/Parsers/PNSubscribeParser.m',
    './Network/Parsers/PNTimeParser.m',
    './Network/PNNetwork.m',
    './Network/PNNetworkResponseSerializer.m',
    './Network/PNReachability.m',
    './Network/PNRequestParameters.m',
    './Network/PNURLBuilder.m',
]

features = [
]

Import('env')
env.BuildLibrary('PubNub', sources, header_paths=header_paths, static=True, flags=flags, defines=defines, deps=deps, features=features)
